### ISSUE TITLE
您好，按照步骤操作的，还是403，请教一下

### ISSUE THREAD

**Issue by LeticiaAnna** [iAJue/qr#2]
您好，按照步骤操作的，还是403，请教一下

public 777
数据库连接改了
伪静态设置了

仍旧403

**Comment by iAJue** [comment]
public设置为对外公开目录，不是设置权限

**Comment by ghost** [comment]
什么是对外公开目录，看球不懂，不是权限是啥，liunx还有别的操作么

**Comment by iAJue** [comment]
请参考thinkPHP5.0 入口文件 说明 https://www.kancloud.cn/manual/thinkphp5/125729

**Comment by ghost** [comment]
不懂，，，

**Comment by LeticiaAnna** [comment]
宝塔的话就是设置为运行目录 不过不知道为什么 设置好了 数据库连完了 访问的时候站点图片全都挂了 而且位置都对不上了

**Comment by 458098895** [comment]
对，就是运行目录啊。没用哎

**Comment by LeticiaAnna** [comment]
宝塔的话 是点站点属性 - 网站目录 - 运行目录 改为public

部分程序需要指定二级目录作为运行目录，如ThinkPHP5，Laravel

**Comment by ghost** [comment]
运行目录是/一杠。。。点不动

**Comment by ghost** [comment]
好了，谢了

**Comment by iAJue** [comment]
图片显示不了，你看图片的地址是什么，然后排错

**Comment by Baiyuetribe** [comment]
> 宝塔的话就是设置为运行目录 不过不知道为什么 设置好了 数据库连完了 访问的时候站点图片全都挂了 而且位置都对不上了

我也是同样的问题
