### ISSUE TITLE
通过phpmyAdmin将pay.sql导入MySQL5.7出现问题，以及能否考虑加入收款监控功能？

### ISSUE THREAD

**Issue by ZeusGamingPlay** [iAJue/qr#3]
如题，监控支付宝、财付通、微信钱包订单的支付状态，并在网站提供显示。
这样的话可以更方便得对接其他网站，便于回调。

**Comment by ZeusGamingPlay** [comment]
数据库导入phpMyAdmin出错
错误
静态分析：

分析时发现2个错误。

Unexpected beginning of statement. (near "REATE" at position 0)
Unrecognized statement type. (near "TABLE" at position 6)
SQL 查询：

REATE TABLE `qr` ( `id` int(11) NOT NULL AUTO_INCREMENT, `qr` varchar(128) NOT NULL DEFAULT '', `name` varchar(10) NOT NULL DEFAULT '', `alipay` varchar(255) NOT NULL DEFAULT '', `qq` varchar(255) NOT NULL DEFAULT '', `wechat` varchar(255) NOT NULL DEFAULT '', `time` int(11) NOT NULL DEFAULT '0', `ip` varchar(128) NOT NULL DEFAULT '', PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8

MySQL 返回： 文档

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'REATE TABLE `qr` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `qr` varchar(128) N' at line 1

**Comment by iAJue** [comment]
重新下载sql文件导入。
另外一个问题不在这个项目的范畴内
