### ISSUE TITLE
样式图片报错！

### ISSUE THREAD

**Issue by qingshanking** [iAJue/qr#5]
![qq 20180829171407](https://user-images.githubusercontent.com/22401257/44778242-13865f80-abaf-11e8-92f8-fff2dd788aeb.png)
请问一下，这个如何解决呢？

**Comment by iAJue** [comment]
这就是没有按步骤做的后果，最简单的方法就是删除项目重新下载

**Comment by qingshanking** [comment]
按照了，然后重新更新了一些项目就没事了，谢谢。
